<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo(a) Admin(a)
        </div>
    </div>
    <?php
    // objeto form contato
    $form = $this->form;
    // preparar elementos do formulário
    $form->prepare();
    // configurar url formulário
    $form->setAttribute('action', $this->url('admin-admin/default', array('controller' => 'admin', 'action' => 'inserir')));

    // renderiza html <form> com atributos configurados no objeto
    echo $this->form()->openTag($form) ?>
    <div class="panel-body ">
        <div class="container">

            
            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Nome .:</label>
                    <div class='col-lg-4  col-md-4'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('nome'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('nome'));
                        ?>
                    </div>
                </div>
            </div>
                  
            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Login .:</label>
                    <div class='col-lg-4  col-md-4'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('login'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('login'));
                        ?>
                    </div>
                </div>
            </div>
                  
            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Senha .:</label>
                    <div class='col-lg-4  col-md-4'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('senha'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('senha'));
                        ?>
                    </div>
                </div>
            </div>
                  
            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Email .:</label>
                    <div class='col-lg-4  col-md-4'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($form->get('email'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('email'));
                        ?>
                    </div>
                </div>
            </div>
                  
            <div class='row'>
                <div class='form-group'>
                    <label for='inputTelefonePrincipal' class='col-md-1 control-label label_right'>Status .:</label>
                    <div class='col-lg-4  col-md-4'>
                        <?php
                        // renderiza html input
                        echo $this->formSelect($form->get('status'));

                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat("<small class='text-danger'>")
                            ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                            ->setMessageCloseString("</small>")
                            ->render($form->get('status'));
                        ?>
                    </div>
                </div>
            </div>
                  
        </div>
    </div>

    <div class="panel-footer">
        <button type="submit" class="btn btn-primary">Salvar Admin(a)</button>
        <a href="<?php echo $this->url('admin-admin'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php
    // renderiza html
    echo $this->form()->closeTag() ?>
</div>